### PR TITLE
Notify release to all killer's victims

### PR DESCRIPTION
**Pull request by Wohoo-GC**
Notify release to all killer's victims and log it on console

### CODE REVIEW

**Comment by Teelevision** [comment]
I'm worried that it would spam the chat for many players in some scenarios. Some people use releasing not only once, but release all players they caught at once.
The console logging would be great though.

**Comment by Wohoo-GC** [comment]
i can create two different commit?
however it would not be spam, because message is delivered only to players that was killed by same person.
If you kill one and release him, noone will receive the message.

**Comment by Teelevision** [comment]
If you catch 8 players and release all of them, the first catched will receive 7 additional messages, the second 6 messages, and so on. This are way to many messages.
You can make a second pull request for the logging if you want.

**Comment by Wohoo-GC** [comment]
Do you prefer commented lines?
Or leave only part related to console?

**Comment by Wohoo-GC** [comment]
And what about the message:
"xx joined the server and is spectating you" ?
Not always, playing, I can see a change in color skin, when someoneelse join the server.

**Comment by Teelevision** [comment]
Comments aren't bad.
The color should not change due to spectators. If it does, which I'm not aware of, it is a bug. A message would be possible, but is not needed in my opinion.

**Pull request closed without merging**
